{
  "Description": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0.",
  "Severity": "UNKNOWN",
  "Score": 0.0
}