{
  "Description": "An issue was discovered TensorFlow v2.18.0. A Denial of Service (DoS) occurs when padding is set to 'valid' in tf.keras.layers.Conv2D.",
  "Severity": "UNKNOWN",
  "Score": 0.0
}